#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

echo ''

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

install_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink.generated' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src//.symlink.generated}")"
    link_file "$src" "$dst"
  done
}

replace_variables () {
  info "replacing variables"

  while read line
  do
    setting="$( echo "$line" | cut -d '=' -f 1 )"
    value="$( echo "$line" | cut -d '=' -f 2- )"

    success=1
    for template in $(find . -type f -name "*.template" \
	    ! -path "./.git/*")
    do
      sed -e "s;%${setting}%;${value};g" $template > "${template//.template/}.generated"

      if [ $? != 0 ]
      then
	success=0
      fi
    done

    if [ $success == 1 ]
    then
      success "${setting} = ${value}"
    else
      fail "${setting} = ${value}"
    fi
  done < config
}

check_existing_variables () {
  info "checking existing variables"

  while read line
  do
    filename="$( echo "$line" | cut -d ':' -f 1 )"
    variable="$( echo "$line" | cut -d ':' -f 2- )"

    matches=$(cut -d "=" -f 1 config | grep "^$variable$" | wc -l)
    if [ $matches == 0 ]
    then
      fail "Variable $variable in use in file '$filename' but not declared in config file"
    fi
  done < <(grep -ERo "%[A-Z_]+%" --include *.template | sort | uniq | tr -d "%")

  success "All variables are configured"
}

check_existing_variables
replace_variables
install_dotfiles

echo ''
echo '  All installed!'
